source 'https://rubygems.org'

gem 'rack', '~> 1.4.5'
gem 'jimson'
gem 'sinatra'
gem 'sinatra-contrib' # for cookies
gem 'activesupport'
gem 'activerecord', '~> 4.1.7'
gem 'omniauth-twitter'
gem 'sqlite3'
gem 'slim'
gem 'ridgepole'
gem 'lockfile', '~> 2.1.3'
gem 'twitter'
gem 'rack-flash3'
gem 'sanitize'
