require_relative 'account'
require_relative 'admin'
require_relative 'broadcast'
require_relative 'channels'
require_relative 'doc'
require_relative 'login'
require_relative 'main'
require_relative 'notices'
require_relative 'profile'
require_relative 'programs'
require_relative 'servents'
require_relative 'screen_shots'
require_relative 'bbs'
# require_relative 'index_txt'
if ENV['PCGW_ENV'] == 'development'
  require_relative 'debug'
end
